services:
  inn_task_mysql:
    image: 'mysql:latest'
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: inncontrol_tasks

  task_app:
    build: ./
    image: sha256:61fd6d9e59a1c4f675d9bd3c2d88e9f17c584ca27f2ec312ef1ec8ec0ce4833c
    ports:
      - "8045:8045"
    environment:
      DB_URL: jdbc:mysql://inn_task_mysql:3306/inncontrol_tasks?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: root

    depends_on:
      - inn_task_mysql