services:
  inn_task_mysql:
    image: 'mysql:latest'
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: inncontrol_tasks

  task_app:
    build: ./
    image: hmarcelorenteriap/inncontrol-task:latest
    ports:
      - "8045:8045"
    environment:
      DB_URL: jdbc:mysql://inn_task_mysql:3306/inncontrol_tasks?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: root

    depends_on:
      - inn_task_mysql